_target_: models.net.gatv2_multidigraph.GATv2MultiDiGraphNet
num_layers: 2
node_features: 2
edge_features: 4
hidden_features: 32
graph_features: -1
gate: bidirect
heads: 3
concat: True
layer_norm: True
